### ISSUE TITLE
override vs overrides misspelling

### ISSUE THREAD

**Issue by Kerwood** [metalbear-co/mirrord.dev#120]
There are few spelling mistakes in the docs regarding the `feature.env.override` option where it is written as `overrides`.

 - https://github.com/metalbear-co/mirrord.dev/blob/main/content/docs/overview/configuration.md?plain=1#L66
 - https://github.com/metalbear-co/mirrord.dev/blob/main/content/docs/overview/configuration.md?plain=1#L392
 - https://github.com/metalbear-co/mirrord.dev/blob/main/content/docs/overview/configuration.md?plain=1#L546

**Comment by t4lz** [comment]
We need to fix those mistakes in https://github.com/metalbear-co/mirrord
