### ISSUE TITLE
"On This Page" section should be hidden when empty

### ISSUE THREAD

**Issue by Razz4780** [metalbear-co/mirrord.dev#195]
Docs subpages contain two navbars: main on the left and "ON THIS PAGE" on the right. They could be improved:
1. The left one does not scale - no matter how big the screen is, the navbar displays the same amount of entries and the scroll is always visible. It's easy to miss the content. Especially the "mirrord for Teams" section, which is the last one on the list
![image](https://github.com/metalbear-co/mirrord.dev/assets/34063647/fa892add-d9cf-4ec2-adeb-8dcf1450f4b1)

2. The right one could be hidden when empty
![image](https://github.com/metalbear-co/mirrord.dev/assets/34063647/8667ad7a-41cf-4f61-b9f3-db65e452cfe3)

**Comment by eyalb181** [comment]
@Razz4780 Are both still relevant with the new docs?

**Comment by Razz4780** [comment]
First one is not, second one still is
![image](https://github.com/metalbear-co/mirrord.dev/assets/34063647/feb97e3b-ff98-404b-a55f-c4a31acea301)
