### ISSUE TITLE
Add preview to search

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord.dev#231]
> It would be helpful to show a preview of the matched text instead of just the page title and description in the search result popover. For example, when searching for "IntelliJ" to find more details about the IntelliJ IDE plugin, I found it difficult to choose the right page containing what I was looking for (I even though the search was broken initially).

from [Discord](https://discord.com/channels/933706914808889356/1001193211152318525/1204712768394100746)

Possible solution:
https://github.com/cloudcannon/pagefind

**Comment by infiniteregrets** [comment]
closed by #237
