### ISSUE TITLE
Section headings not rendering in config reference docs

### ISSUE THREAD

**Issue by gememma** [metalbear-co/mirrord.dev#370]
![Screenshot 2024-12-05 at 10 50 36](https://github.com/user-attachments/assets/0db7c5b4-d3b1-487f-b24b-5a6b0993e645)

Headings for sections `feature.network.incoming.http_filter.header_filter/path_filter/ports` render as if they're normal paragraph text (but they're still links)

**Comment by aviramha** [comment]
Isn't that dup of https://github.com/metalbear-co/mirrord.dev/issues/284 ?

**Comment by gememma** [comment]
Good point 👀 closed as duplicate of #284
