### ISSUE TITLE
Revamp the configuration view

### ISSUE THREAD

**Issue by eyalb181** [metalbear-co/mirrord.dev#69]
Our current configuration view is pretty much unusable, we should find a better way to display it. 

One possible way to do it is with https://json-schema.app/view/%23%2Fdefinitions%2FFeatureFileConfig?url=https://raw.githubusercontent.com/metalbear-co/mirrord/main/mirrord-schema.json.

**Comment by meowjesty** [comment]
Style question:

### :lobster: Should the parts that contain examples be a full working example doc, such as:

```json
{
  "target": "pod/foo-pod",
  "feature": {
    "network": "incoming",
  }
}
```

### :crab:  Or should they represent only what they're documenting:

```json
{
  "network": "incoming",
}
```

**Comment by t4lz** [comment]
Suggesting a third option: 

Just the value that is being discussed in that section, but including all ancestors up to the root:

```json
{
  "feature": {
    "network": "incoming",
  }
}
```

**Comment by eyalb181** [comment]
@meowjesty First task can be checked off, right? Anything else?

**Comment by meowjesty** [comment]
The only remaining task is adding example validation to the tool, should I leave this issue open, or close it and open a new one for this specific thing?

**Comment by eyalb181** [comment]
Lets close this one and open a new specific issue
